/**
 * Generates lib/company-logos.ts from simple-icons (CC0 brand SVGs).
 *
 *   npm run gen:logos
 *
 * We pin simple-icons@9 as a devDependency because newer majors dropped many
 * large-brand icons (Amazon, Microsoft, Adobe, Oracle…) over trademark
 * takedowns. Only the extracted path/hex data ships — no runtime dependency.
 */
const fs = require("fs");
const path = require("path");
const si = require("simple-icons");

const ROOT = path.join(__dirname, "..");
const raw = require(path.join(ROOT, "data", "problems.json"));

// Index every icon by slug and by normalized title.
const bySlug = new Map();
const byTitle = new Map();
for (const key of Object.keys(si)) {
  const ic = si[key];
  if (!ic || !ic.slug || !ic.path) continue;
  bySlug.set(ic.slug, ic);
  byTitle.set(ic.title.toLowerCase().replace(/[^a-z0-9]/g, ""), ic);
}

const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

// Company name -> simple-icons slug, for sub-brands and non-obvious matches.
const OVERRIDE = {
  Alibaba: "alibabadotcom",
  "Amazon Web Services": "amazonaws",
  "Amazon Music": "amazon",
  "Apple Maps": "apple",
  "Google Cloud": "googlecloud",
  "Microsoft Azure": "microsoftazure",
  "Microsoft Teams": "microsoftteams",
  "Walmart Labs": "walmart",
  UberEats: "ubereats",
  Doordash: "doordash",
  DoorDash: "doordash",
  "Disney+": "disneyplus",
  "Booking.com": "bookingdotcom",
  "Epic Games": "epicgames",
  "Electronic Arts": "ea",
  "Goldman Sachs": "goldmansachs",
  "New Relic": "newrelic",
  "Pure Storage": "purestorage",
  MathWorks: "mathworks",
  X: "x",
  HBO: "hbo",
  Hulu: "hulu",
  SAP: "sap",
  IBM: "ibm",
  UPS: "ups",
  FedEx: "fedex",
  VMware: "vmware",
  Yahoo: "yahoo",
  Square: "square",
};

function findIcon(name) {
  if (name in OVERRIDE) return bySlug.get(OVERRIDE[name]) || null;
  const n = norm(name);
  return byTitle.get(n) || bySlug.get(n) || bySlug.get(n.replace(/com$/, "dotcom")) || null;
}

const names = new Set();
for (const p of raw) {
  if (p.primary_company) names.add(p.primary_company);
  for (const c of p.companies || []) if (c) names.add(c);
}

const slugify = (name) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const out = {};
const misses = [];
for (const name of [...names].sort()) {
  const ic = findIcon(name);
  if (ic) out[slugify(name)] = { p: ic.path, c: ic.hex, t: ic.title };
  else misses.push(name);
}

const lines = [
  "// AUTO-GENERATED by scripts/gen-logos.js — do not edit by hand.",
  "// Brand SVG paths + hex from simple-icons (CC0). Keyed by company slug.",
  "export interface LogoData { p: string; c: string; t: string }",
  "export const LOGOS: Record<string, LogoData> = {",
  ...Object.entries(out).map(
    ([slug, d]) =>
      `  ${JSON.stringify(slug)}: { p: ${JSON.stringify(d.p)}, c: ${JSON.stringify(d.c)}, t: ${JSON.stringify(d.t)} },`
  ),
  "};",
  "",
];
fs.writeFileSync(path.join(ROOT, "lib", "company-logos.ts"), lines.join("\n"));

console.log(`Matched ${Object.keys(out).length} logos, ${misses.length} monogram fallbacks.`);
if (misses.length) console.log("Fallbacks:", misses.join(", "));
